"""Add ACT phase fields

Revision ID: 03e7010c259c
Revises: 8ad6a4374857
Create Date: 2026-05-09 00:18:23.326880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e7010c259c'
down_revision: Union[str, Sequence[str], None] = '8ad6a4374857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdsacycle', sa.Column('act_decision', sa.String(), nullable=True))
    op.add_column('pdsacycle', sa.Column('act_notes', sa.Text(), nullable=True))
    op.add_column('pdsacycle', sa.Column('act_next_steps', sa.Text(), nullable=True))
    op.add_column('pdsacycle', sa.Column('act_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdsacycle', 'act_completed_at')
    op.drop_column('pdsacycle', 'act_next_steps')
    op.drop_column('pdsacycle', 'act_notes')
    op.drop_column('pdsacycle', 'act_decision')
    # ### end Alembic commands ###
