"""add_projects_table

Revision ID: 27d882e2e56f
Revises: 03e7010c259c
Create Date: 2026-06-18 23:31:40.290135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d882e2e56f'
down_revision: Union[str, Sequence[str], None] = '03e7010c259c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.add_column('pdsacycle', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pdsacycle_project_id'), 'pdsacycle', ['project_id'], unique=False)
    op.create_foreign_key(None, 'pdsacycle', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdsacycle', type_='foreignkey')
    op.drop_index(op.f('ix_pdsacycle_project_id'), table_name='pdsacycle')
    op.drop_column('pdsacycle', 'project_id')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
