"""Add DO phase fields

Revision ID: 71984e5e34b0
Revises: c24fcdd9c3b6
Create Date: 2026-05-08 23:53:59.632785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71984e5e34b0'
down_revision: Union[str, Sequence[str], None] = 'c24fcdd9c3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdsacycle', sa.Column('do_observations', sa.Text(), nullable=True))
    op.add_column('pdsacycle', sa.Column('do_data_collected', sa.Text(), nullable=True))
    op.add_column('pdsacycle', sa.Column('do_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdsacycle', 'do_completed_at')
    op.drop_column('pdsacycle', 'do_data_collected')
    op.drop_column('pdsacycle', 'do_observations')
    # ### end Alembic commands ###
