"""Add STUDY phase fields

Revision ID: 8ad6a4374857
Revises: 71984e5e34b0
Create Date: 2026-05-08 23:59:31.556131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad6a4374857'
down_revision: Union[str, Sequence[str], None] = '71984e5e34b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdsacycle', sa.Column('study_analysis', sa.Text(), nullable=True))
    op.add_column('pdsacycle', sa.Column('study_hypothesis_confirmed', sa.String(), nullable=True))
    op.add_column('pdsacycle', sa.Column('study_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdsacycle', 'study_completed_at')
    op.drop_column('pdsacycle', 'study_hypothesis_confirmed')
    op.drop_column('pdsacycle', 'study_analysis')
    # ### end Alembic commands ###
