"""Add PDSACycle model

Revision ID: c24fcdd9c3b6
Revises: 826800eff07e
Create Date: 2026-05-08 23:40:47.111552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24fcdd9c3b6'
down_revision: Union[str, Sequence[str], None] = '826800eff07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdsacycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aim', sa.Text(), nullable=False),
    sa.Column('measure', sa.Text(), nullable=False),
    sa.Column('change_idea', sa.Text(), nullable=False),
    sa.Column('available_hypotheses', sa.JSON(), nullable=True),
    sa.Column('suggested_metrics', sa.JSON(), nullable=True),
    sa.Column('power_analysis', sa.Text(), nullable=True),
    sa.Column('selected_hypothesis', sa.Text(), nullable=True),
    sa.Column('selected_rationale', sa.Text(), nullable=True),
    sa.Column('user_observations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdsacycle_id'), 'pdsacycle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdsacycle_id'), table_name='pdsacycle')
    op.drop_table('pdsacycle')
    # ### end Alembic commands ###
